### ISSUE TITLE
can I use it on Tizen wearable?

### ISSUE THREAD

**Issue by dsdlsu** [intel/fMBT#65]
Hello.
I would like to use it on Tizen wearable such as Galaxy gear.
Would that be possible?

**Comment by askervin** [comment]
Hi,

I can't promise that everything would work, because I haven't tried fmbttizen with Tizen wearables. But changes are good that at you'll find many working features.

I'd suggest trying out
```
import fmbttizen
help(fmttizen.Device)
```
and choosing parameters so that they match the way how you connect to the device (sdb or ssh).

A couple of Tizen engineers have been active on this forum some time ago. You might find very useful information from their comments as well.

**Comment by dsdlsu** [comment]
> 
> 
> Hi,
> 
> I can't promise that everything would work, because I haven't tried fmbttizen with Tizen wearables. But changes are good that at you'll find many working features.
> 
> I'd suggest trying out
> 
> ```
> import fmbttizen
> help(fmttizen.Device)
> ```
> 
> and choosing parameters so that they match the way how you connect to the device (sdb or ssh).
> 
> A couple of Tizen engineers have been active on this forum some time ago. You might find very useful information from their comments as well.

**Comment by dsdlsu** [comment]
Hello,
I have checked it is working well on my Gear device.
Thank you^^
