### ISSUE TITLE
fmbt-scripter.exe  error

### ISSUE THREAD

**Issue by THADARTH** [intel/fMBT#70]
**I installed fmbt on my computer and when I try to use fmbt-scripter.exe by clicking on  file -> new Android, I get the bellow error. I have tried to correct this error but without success .**

>>> 
exec: import fmbtandroid
time: 0.000 s
>>> 
exec: sut = fmbtandroid.Device()
time: 1.908 s
>>> 
exec: sut.refreshScreenshot()
exception: [Error 2] Le fichier spécifié est introuvable: 'C:\\Program Files\\fMBT\\screenshots\\20190605-145406-527000-04cdda6a00747559.png'
  Traceback (most recent call last):    
  File "C:\Program Files\fMBT\fmbt-scripter", line 1999, in _fmbtExec    
    exec statement in self._fmbtEnv    
  File "<string>", line 1, in <module>    
  File "C:\Python27\lib\fmbtandroid.py", line 1036, in refreshScreenshot    
    return self.refreshScreenshot(forcedScreenshot, rotate=-drot)    
  File "C:\Python27\lib\fmbtandroid.py", line 1037, in refreshScreenshot    
    rv = fmbtgti.GUITestInterface.refreshScreenshot(self, forcedScreenshot, rotate)    
  File "C:\Python27\lib\fmbtgti.py", line 1791, in refreshScreenshot    
    if self.existingConnection().recvScreenshot(screenshotFile):    
  File "C:\Python27\lib\fmbtandroid.py", line 3095, in recvScreenshot    
    if os.path.getsize(filename) == 0:    
  File "C:\Python27\lib\genericpath.py", line 57, in getsize    
    return os.stat(filename).st_size    
WindowsError: [Error 2] Le fichier spécifié est introuvable: 'C:\\Program Files\\fMBT\\screenshots\\20190605-145406-527000-04cdda6a00747559.png'
>>> 
time: 5.640 s
>>> 
refreshScreenshot() returned None
>>> 

--------------------------------------------------------------------------------------------------
IMconvert.exe: UnableToOpenConfigureFile `type.xml' @ warning/configure.c/GetConfigureOptions/706.
IMconvert.exe: DelegateLibrarySupportNotBuiltIn `c:\windows\fonts\arial.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1533.
IMconvert.exe: UnableToOpenBlob `C:/Users/UTILIS~1/AppData/Local/Temp/magick-41441x4EsPoi0CxK': No such file or directory @ error/blob.c/OpenBlob/2709.
IMconvert.exe: DelegateLibrarySupportNotBuiltIn `c:\windows\fonts\arial.ttf' (Freetype) @ warning/annotate.c/RenderFreetype/1533.
IMconvert.exe: UnableToOpenBlob `C:/Users/UTILIS~1/AppData/Local/Temp/magick-41447RZcnvTJWwb9': No such file or directory @ error/blob.c/OpenBlob/2709.
IMconvert.exe: UnableToOpenConfigureFile `colors.xml' @ warning/configure.c/GetConfigureOptions/706.
IMconvert.exe: NoImagesDefined `C:\Program Files\fMBT\screenshots\screenshot-error-1080x1920.png' @ error/convert.c/ConvertImageCommand/3210.

-------------------------------------------------------------------------------------------------------
@rseymour @argretzi @askervin @pablovirolainen @igor-stoppa 
![Capture](https://user-images.githubusercontent.com/37008499/58957923-00d63200-87a2-11e9-9ba4-f41e03f109c6.PNG)

**Comment by askervin** [comment]
Hi, @THADARTH,

Could it be that you are running `fmbt-scripter.exe` in a directory where the user does not have write permissions?

Try creating a new directory under which you could develop the test script:
```
mkdir mydir
cd mydir
fmbt-scripter.exe myscript.py
```

Longer explanation for understanding why:

`fmbt-scripter` runs few lines in your test script to help you developing the script. In particular, `import fmbtxxxx` and a line like `dut = fmbtxxxx.Device()`. That's why `fmbt-scripter` will be able to connect to the device that you'd like to test: a mobile device with correct ID, or a Windows device behind correct IP address, for instance. When `fmbt-scripter.exe` takes a screenshot on the device under test, it uses exactly the same object as your script. It is the method of this object (`fmbtandroid.Device.refreshScreenshot`, for instance) that wants to save screenshots under the current working directory. The same thing happens when you run your test script without `fmbt-scripter`. Therefore write permissions to the current working directory are needed.

-- Antti

**Comment by THADARTH** [comment]
@askervin  thank you for your hints. I changed the permissions of the folder and now, it working
